# Generated by Django 4.2.5 on 2023-09-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('attribute', models.CharField(choices=[('1', 'Fire'), ('2', 'Water'), ('3', 'Thunder'), ('4', 'Ice'), ('5', 'Dragon')], max_length=1)),
                ('weakness', models.CharField(max_length=20)),
                ('rank', models.CharField(choices=[('9', 'Hunter Rank 9'), ('8', 'Hunter Rank 9'), ('7', 'Hunter Rank 9'), ('6', 'Hunter Rank 9'), ('5', 'Hunter Rank 9'), ('4', 'Hunter Rank 9'), ('3', 'Hunter Rank 9'), ('2', 'Hunter Rank 9'), ('1', 'Hunter Rank 9')], max_length=1)),
            ],
        ),
    ]
