# Generated by Django 4.2.5 on 2023-09-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_monster_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='attribute',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Water', 'Water'), ('Thunder', 'Thunder'), ('Ice', 'Ice'), ('Dragon', 'Dragon')], max_length=15),
        ),
    ]
